### ISSUE TITLE
Fixes for ssd_mobilenetv1

### ISSUE THREAD

**Issue by ojotoxy** [latentai/model-zoo-models#6]
- (Start by pulling in changes, we did some formatting changes to the code & readme.)
- Merge generate_detections.py and eval.py into the same script -- 1 step process to call.
- demo.py should output text/json results to console in addition to the image.
- None of the compile example command lines work, please fix
- Please upload trained keras model and tf checkpoint to s3 using "zoo-hash-upload" and add the weights files to models_index.json in the root of the repo. (Look at vgg16 as an example - although vgg16 has been trained on 2 different datasets. Put the dataset name in the variant name.)
- Document how to download the trained model with "leip zoo download --model_id .... --variant_id ..." and use it for evaluation.

**Comment by bohdankornienko** [comment]
> demo.py should output text/json results to console in addition to the image.

Can you provide sample output to be clear on how it supposed to look?

**Comment by bohdankornienko** [comment]
Please see https://github.com/latentai/model-zoo-models/pull/10
