### ISSUE TITLE
Fixes for ssd_mobilenetv2

### ISSUE THREAD

**Issue by ojotoxy** [latentai/model-zoo-models#7]
- (Start by pulling in changes, we did some formatting changes to the code & readme.)
- Explain in much more detail what the "Configure Settings" section is about. Where to save it, what needs to be edited.
- Show how to download the dataset with leip zoo download.
- Show how to use the downloaded dataset with training.
- Merge prepare_eval_data.py and eval.py into the same script/process. Eval should be 1 step.
- demo.py should print text/json to console in addition to the image. So it can be used on command line easily.
- Show how to download the pre-trained weights. Show how to use the pre-trained weights for eval.
- Can voc_2007.pkl be moved into part of the dataset? The training code should not be dependent on the dataset. Training should be able to be used across multiple datasets easily.
- Show how to use "leip compile" like the readme in ssd_mobilenetv1 does.
- Please upload trained tf checkpoint to s3 using "zoo-hash-upload" and add the weights files to models_index.json in the root of the repo. (Look at vgg16 as an example - although it looks like you only are saving the tf checkpoint here, not the keras model.)

**Comment by vhamolya** [comment]
@ojotoxy Comments will be implemented in the next PR. One question, how demo.py output should look like?
